import type { WeatherData } from './weather';

export const mockWeatherData: WeatherData = {
  city: {
    id: 3448439,
    name: 'São Paulo',
    country: 'Brasil',
    countryCode: 'BR',
    admin1: 'São Paulo',
    latitude: -23.5505,
    longitude: -46.6333,
    timezone: 'America/Sao_Paulo',
    label: 'São Paulo, São Paulo, Brasil',
  },
  current: {
    temperatureC: 23.4,
    weatherCode: 2,
    weatherDescription: 'Parcialmente nublado',
    humidity: 68,
    windSpeed: 12.6,
    pressure: 1014,
    precipitation: 0,
    observationTime: '2026-09-02T14:00:00-03:00',
  },
  forecast: [
    {
      date: '2026-09-02',
      dayLabel: 'Hoje',
      weatherCode: 2,
      weatherDescription: 'Parcialmente nublado',
      minTemperatureC: 16.8,
      maxTemperatureC: 25.1,
      precipitationProbability: 20,
      precipitationSum: 0,
    },
    {
      date: '2026-09-03',
      dayLabel: 'Qui',
      weatherCode: 3,
      weatherDescription: 'Nublado',
      minTemperatureC: 17.2,
      maxTemperatureC: 24.3,
      precipitationProbability: 35,
      precipitationSum: 0.4,
    },
    {
      date: '2026-09-04',
      dayLabel: 'Sex',
      weatherCode: 61,
      weatherDescription: 'Chuva fraca',
      minTemperatureC: 16.4,
      maxTemperatureC: 21.8,
      precipitationProbability: 70,
      precipitationSum: 4.8,
    },
    {
      date: '2026-09-05',
      dayLabel: 'Sáb',
      weatherCode: 80,
      weatherDescription: 'Pancadas de chuva',
      minTemperatureC: 15.9,
      maxTemperatureC: 22.5,
      precipitationProbability: 60,
      precipitationSum: 2.6,
    },
    {
      date: '2026-09-06',
      dayLabel: 'Dom',
      weatherCode: 1,
      weatherDescription: 'Predominantemente limpo',
      minTemperatureC: 15.1,
      maxTemperatureC: 26.7,
      precipitationProbability: 10,
      precipitationSum: 0,
    },
  ],
};
